version: '3.8'

services:
  db:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: productivity_hub_development
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  web:
    build: .
    platform: linux/x86_64
    command: ["./bin/dev"]
    volumes:
      - .:/productivity-hub
    ports:
      - "3000:3000"
    depends_on:
      - db

  setup:
    build: .
    command: ["bundle", "exec", "rails", "db:setup"]
    volumes:
      - .:/productivity-hub
    depends_on:
      - db

volumes:
  mysql_data:
